stages:
  ingest:
    cmd: python src/ingest.py
    deps:
    - src/ingest.py
    outs:
    - data/raw/data.csv
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/data.csv
    - src/preprocess.py
    outs:
    - data/processed/data.csv
    - models/preprocessor.pkl
  train:
    cmd: python src/train.py
    deps:
    - data/processed/data.csv
    - src/train.py
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed/data.csv
    - models/model.pkl
    - src/evaluate.py
    outs:
    - models/evaluation.json
